# Generated by Django 4.2.13 on 2024-11-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_recipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
