# Generated by Django 4.2.13 on 2024-06-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPage',
        ),
    ]
